services:
  frontend: 
    container_name: cnblog_theme
    build: 
      context: ./
      dockerfile: .Dockerfile
    image: cnblog_theme:${VERSION:-latest}
    restart: always
    
    environment:
      WEB_PORT: ${WEB_PORT:-5100}
    ports:
      - ${APP_PORT:-3010}:${WEB_PORT:-80}