services:
  frontend: 
    container_name: cnblog_theme
    build: 
      context: ./
      dockerfile: .Dockerfile
    image: cnblog_theme:${VERSION:-latest}
    restart: always
    
    environment:
      WEB_PORT: ${WEB_PORT:-80}
      API_PORT: ${APP_PORT:-3000}
    ports:
      - ${APP_PORT:-3000}:${WEB_PORT:-80}
      - 443:443
